//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.03 at 10:31:51 PM CEST 
//


package calafie.builder.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for capacite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="capacite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="niveau" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ordres" type="{calafie/builder/ordre}ordres" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "capacite", propOrder = {
    "nom",
    "niveau",
    "ordres"
})
public class Capacite {

    @XmlElement(required = true)
    protected String nom;
    protected int niveau;
    protected Ordres ordres;

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the niveau property.
     * 
     */
    public int getNiveau() {
        return niveau;
    }

    /**
     * Sets the value of the niveau property.
     * 
     */
    public void setNiveau(int value) {
        this.niveau = value;
    }

    /**
     * Gets the value of the ordres property.
     * 
     * @return
     *     possible object is
     *     {@link Ordres }
     *     
     */
    public Ordres getOrdres() {
        return ordres;
    }

    /**
     * Sets the value of the ordres property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ordres }
     *     
     */
    public void setOrdres(Ordres value) {
        this.ordres = value;
    }

}
