//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.14 at 02:07:25 AM CEST 
//


package calafie.builder.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the calafie.builder.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fiche_QNAME = new QName("calafie/builder/fiche", "fiche");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: calafie.builder.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VocationType }
     * 
     */
    public VocationType createVocationType() {
        return new VocationType();
    }

    /**
     * Create an instance of {@link Competences }
     * 
     */
    public Competences createCompetences() {
        return new Competences();
    }

    /**
     * Create an instance of {@link Caracteristiques }
     * 
     */
    public Caracteristiques createCaracteristiques() {
        return new Caracteristiques();
    }

    /**
     * Create an instance of {@link Fiche }
     * 
     */
    public Fiche createFiche() {
        return new Fiche();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fiche }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "calafie/builder/fiche", name = "fiche")
    public JAXBElement<Fiche> createFiche(Fiche value) {
        return new JAXBElement<Fiche>(_Fiche_QNAME, Fiche.class, null, value);
    }

}
