//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 11:16:02 AM CEST 
//


package org.calafie.old;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caracteristiques complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="caracteristiques">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="force" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="volonte" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="charisme" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gestion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="intelligence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="perception" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caracteristiques", namespace = "calafie/builder/fiche", propOrder = {
    "force",
    "volonte",
    "charisme",
    "gestion",
    "intelligence",
    "perception"
})
public class Caracteristiques {

    protected int force;
    protected int volonte;
    protected int charisme;
    protected int gestion;
    protected int intelligence;
    protected int perception;

    /**
     * Gets the value of the force property.
     * 
     */
    public int getForce() {
        return force;
    }

    /**
     * Sets the value of the force property.
     * 
     */
    public void setForce(int value) {
        this.force = value;
    }

    /**
     * Gets the value of the volonte property.
     * 
     */
    public int getVolonte() {
        return volonte;
    }

    /**
     * Sets the value of the volonte property.
     * 
     */
    public void setVolonte(int value) {
        this.volonte = value;
    }

    /**
     * Gets the value of the charisme property.
     * 
     */
    public int getCharisme() {
        return charisme;
    }

    /**
     * Sets the value of the charisme property.
     * 
     */
    public void setCharisme(int value) {
        this.charisme = value;
    }

    /**
     * Gets the value of the gestion property.
     * 
     */
    public int getGestion() {
        return gestion;
    }

    /**
     * Sets the value of the gestion property.
     * 
     */
    public void setGestion(int value) {
        this.gestion = value;
    }

    /**
     * Gets the value of the intelligence property.
     * 
     */
    public int getIntelligence() {
        return intelligence;
    }

    /**
     * Sets the value of the intelligence property.
     * 
     */
    public void setIntelligence(int value) {
        this.intelligence = value;
    }

    /**
     * Gets the value of the perception property.
     * 
     */
    public int getPerception() {
        return perception;
    }

    /**
     * Sets the value of the perception property.
     * 
     */
    public void setPerception(int value) {
        this.perception = value;
    }

}
