//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 11:16:02 AM CEST 
//


package org.calafie.old;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the calafie.builder.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fiche_QNAME = new QName("calafie", "fiche");
    private final static QName _Vocations_QNAME = new QName("calafie", "vocations");
    private final static QName _Ordres_QNAME = new QName("calafie", "ordres");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: calafie.builder.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Vocations }
     * 
     */
    public Vocations createVocations() {
        return new Vocations();
    }

    /**
     * Create an instance of {@link Vocation }
     * 
     */
    public Vocation createVocation() {
        return new Vocation();
    }

    /**
     * Create an instance of {@link Capacite }
     * 
     */
    public Capacite createCapacite() {
        return new Capacite();
    }

    /**
     * Create an instance of {@link Caracteristiques }
     * 
     */
    public Caracteristiques createCaracteristiques() {
        return new Caracteristiques();
    }

    /**
     * Create an instance of {@link Capacites }
     * 
     */
    public Capacites createCapacites() {
        return new Capacites();
    }

    /**
     * Create an instance of {@link Competences }
     * 
     */
    public Competences createCompetences() {
        return new Competences();
    }

    /**
     * Create an instance of {@link Ordres }
     * 
     */
    public Ordres createOrdres() {
        return new Ordres();
    }

    /**
     * Create an instance of {@link Ordre }
     * 
     */
    public Ordre createOrdre() {
        return new Ordre();
    }

    /**
     * Create an instance of {@link VocationType }
     * 
     */
    public VocationType createVocationType() {
        return new VocationType();
    }

    /**
     * Create an instance of {@link Fiche }
     * 
     */
    public Fiche createFiche() {
        return new Fiche();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fiche }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "calafie", name = "fiche")
    public JAXBElement<Fiche> createFiche(Fiche value) {
        return new JAXBElement<Fiche>(_Fiche_QNAME, Fiche.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Vocations }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "calafie", name = "vocations")
    public JAXBElement<Vocations> createVocations(Vocations value) {
        return new JAXBElement<Vocations>(_Vocations_QNAME, Vocations.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ordres }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "calafie", name = "ordres")
    public JAXBElement<Ordres> createOrdres(Ordres value) {
        return new JAXBElement<Ordres>(_Ordres_QNAME, Ordres.class, null, value);
    }

}
